In [4]:
import pandas as pd

In [5]:
data=pd.read_csv('/content/car_price_performance.csv')
data

        Brand  Price  Horsepower  Fuel Efficiency
0     Brand C  91942         382             15.3
1     Brand A  70075         197             32.6
2     Brand C  84524         188             34.9
3     Brand E  68939         258             15.1
4     Brand X  66505         277             13.0
...       ...    ...         ...              ...
1995  Brand Z  34535         196             15.2
1996  Brand C  35215         377             25.3
1997  Brand E  72980         294             21.8
1998  Brand Z  55921         443             11.0
1999  Brand B  95051         225             12.4

[2000 rows x 4 columns]

In [6]:
br=data.groupby('Brand')['Price'].mean().sort_values(ascending=True)
br

Brand
Brand W    63034.557018
Brand E    63712.542601
Brand Y    63880.171569
Brand A    64224.495370
Brand B    64686.641350
Brand C    64707.967890
Brand Z    65244.331818
Brand X    65405.884259
Brand D    65498.701681
Name: Price, dtype: float64

In [7]:
dic={}
for i in range(len(br)):
    dic[br.index[i]]=i+1

In [8]:
l1=[]
for i in range(len(data)):
    l1.append(dic[data['Brand'][i]])

In [9]:
data['Encodede_Brand']=l1
data

        Brand  Price  Horsepower  Fuel Efficiency  Encodede_Brand
0     Brand C  91942         382             15.3               6
1     Brand A  70075         197             32.6               4
2     Brand C  84524         188             34.9               6
3     Brand E  68939         258             15.1               2
4     Brand X  66505         277             13.0               8
...       ...    ...         ...              ...             ...
1995  Brand Z  34535         196             15.2               7
1996  Brand C  35215         377             25.3               6
1997  Brand E  72980         294             21.8               2
1998  Brand Z  55921         443             11.0               7
1999  Brand B  95051         225             12.4               5

[2000 rows x 5 columns]

In [10]:
#MIN-MAX SCALLING
l2=[]
for i in data['Horsepower']:
  l2.append((i-min(data['Horsepower']))/(max(data['Horsepower'])-min(data['Horsepower'])))
data['Scaled_HorsePower']=l2

In [11]:
l3=[]
for i in data['Fuel Efficiency']:
  l3.append((i-min(data['Fuel Efficiency']))/(max(data['Fuel Efficiency'])-min(data['Fuel Efficiency'])))
data['Scaled_Fuel_Efficiency']=l3
data

,Brand,Price,Horsepower,Fuel Efficiency,Encodede_Brand,Scaled_HorsePower,Scaled_Fuel_Efficiency
0,Brand C,91942,382,15.3,6,0.7050,0.212
1,Brand A,70075,197,32.6,4,0.2425,0.904
2,Brand C,84524,188,34.9,6,0.2200,0.996
3,Brand E,68939,258,15.1,2,0.3950,0.204
4,Brand X,66505,277,13.0,8,0.4425,0.120
...,...,...,...,...,...,...,...
1995,Brand Z,34535,196,15.2,7,0.2400,0.208
1996,Brand C,35215,377,25.3,6,0.6925,0.612
1997,Brand E,72980,294,21.8,2,0.4850,0.472
1998,Brand Z,55921,443,11.0,7,0.8575,0.040
1999,Brand B,95051,225,12.4,5,0.3125,0.096

In [12]:
l4=[]
for i in data['Encodede_Brand']:
  l4.append((i-min(data['Encodede_Brand']))/(max(data['Encodede_Brand'])-min(data['Encodede_Brand'])))
data['Scaled_Brand']=l4
data

,Brand,Price,Horsepower,Fuel Efficiency,Encodede_Brand,Scaled_HorsePower,Scaled_Fuel_Efficiency,Scaled_Brand
0,Brand C,91942,382,15.3,6,0.7050,0.212,0.625
1,Brand A,70075,197,32.6,4,0.2425,0.904,0.375
2,Brand C,84524,188,34.9,6,0.2200,0.996,0.625
3,Brand E,68939,258,15.1,2,0.3950,0.204,0.125
4,Brand X,66505,277,13.0,8,0.4425,0.120,0.875
...,...,...,...,...,...,...,...,...
1995,Brand Z,34535,196,15.2,7,0.2400,0.208,0.750
1996,Brand C,35215,377,25.3,6,0.6925,0.612,0.625
1997,Brand E,72980,294,21.8,2,0.4850,0.472,0.125
1998,Brand Z,55921,443,11.0,7,0.8575,0.040,0.750
1999,Brand B,95051,225,12.4,5,0.3125,0.096,0.500

In [13]:
#pi=hp*0.7+f*0.3/p
l5=[]
for i in range(len(data)):
  pi=(data['Horsepower'][i]*0.7+data['Fuel Efficiency'][i]*0.3)/data['Price'][i]
  l5.append(pi)
data['Performance_Index']=l5
data

,Brand,Price,Horsepower,Fuel Efficiency,Encodede_Brand,Scaled_HorsePower,Scaled_Fuel_Efficiency,Scaled_Brand,Performance_Index
0,Brand C,91942,382,15.3,6,0.7050,0.212,0.625,0.002958
1,Brand A,70075,197,32.6,4,0.2425,0.904,0.375,0.002107
2,Brand C,84524,188,34.9,6,0.2200,0.996,0.625,0.001681
3,Brand E,68939,258,15.1,2,0.3950,0.204,0.125,0.002685
4,Brand X,66505,277,13.0,8,0.4425,0.120,0.875,0.002974
...,...,...,...,...,...,...,...,...,...
1995,Brand Z,34535,196,15.2,7,0.2400,0.208,0.750,0.004105
1996,Brand C,35215,377,25.3,6,0.6925,0.612,0.625,0.007709
1997,Brand E,72980,294,21.8,2,0.4850,0.472,0.125,0.002910
1998,Brand Z,55921,443,11.0,7,0.8575,0.040,0.750,0.005604
1999,Brand B,95051,225,12.4,5,0.3125,0.096,0.500,0.001696

In [15]:
data.to_csv("final_data_HariKrishna_691.csv")